
SUBESTACOES = {
    "NUCAP": {
        0: "AUG",
        1: "BQB",
        2: "CQS",
        3: "FAA",
        4: "FCA",
        5: "FIS",
        6: "GCR",
        7: "ICO",
        8: "INE",
        9: "ISL",
        10: "PCN",
        11: "PLA",
        12: "PPA",
        13: "RCO",
        14: "SAI",
        15: "SJR",
        16: "SJS",
        17: "TCO",
        18: "TDE",
        19: "TJS",
    },
    "NUVAL": {
        0: "BBV",
        1: "BFA",
        2: "BGA",
        3: "BND",
        4: "BQE",
        5: "BRB",
        6: "BSO",
        7: "BSP",
        8: "CRI",
        9: "DPO",
        10: "GPR",
        11: "IAL",
        12: "LAS",
        13: "MDA",
        14: "PRE",
        15: "RCC",
        16: "RCP",
        17: "RCS",
        18: "PRA",
        19: "SPO",
        20: "TBO",
    },
    "NUNOR": {
        0: "ACA",
        1: "AHG",
        2: "APG",
        3: "ARI",
        4: "GVA",
        5: "IOA",
        6: "JBV",
        7: "JGM",
        8: "JIU",
        9: "JPI",
        10: "JPM",
        11: "JSC",
        12: "JVC",
        13: "JVN",
        14: "JVQ",
        15: "JVT",
        16: "JVU",
        17: "PRA",
        18: "SFS",
        19: "UTA",
    },
    "NUPLA": {
        0: "AGI",
        1: "BJS",
        2: "BRO",
        3: "CBK",
        4: "CDI",
        5: "CUP",
        6: "LAI",
        7: "LUC",
        8: "LVR",
        9: "OCA",
        10: "PAA",
        11: "SCA",
        12: "SCO",
        13: "SJI",
        14: "SJM",
    },
    "UNVID": {
        0: "CCN",
        1: "CDR",
        2: "FBO",
        3: "TRA",
        4: "VDA",
    },
    "UNCON": {
        0: "ATA",
        1: "COA",
        2: "CSC",
        3: "FGS",
        4: "FUC",
        5: "IRM",
        6: "PAO",
        7: "PSA",
        8: "SRA",
    },
    "UNJSL": {
        0: "CPA",
        1: "GLL",
        2: "GRI",
        3: "GRM",
        4: "JCP",
        5: "JNR",
        6: "JRL",
        7: "JSL",
        8: "SSR",
        9: "SUB",
    },
    "NUMOS": {
        0: "ADE",
        1: "ADP",
        2: "CDS",
        3: "CNB",
        4: "CNS",
        5: "CNU",
        6: "CZL",
        7: "HOE",
        8: "TTS",
        9: "VBA",
    },
    "NUSUL": {
        0: "AGA",
        1: "CFL",
        2: "CUA",
        3: "EMO",
        4: "FLA",
        5: "ICA",
        6: "LMR",
        7: "MJA",
        8: "MUA",
        9: "SIO",
        10: "SRS",
        11: "USA",
    },
    "USNMO": {
        0: "INA",
        1: "MCR",
        2: "MRA",
        3: "PMS",
        4: "SJC",
        5: "SMD",
    },
    "UNTUB": {
        0: "BNB",
        1: "BNE",
        2: "CBX",
        3: "GPA",
        4: "GVL",
        5: "IBA",
        6: "JVA",
        7: "LGA",
        8: "OAS",
        9: "SGO",
        10: "TRD",
        11: "TRO",
    },
    "UNRSL": {
        0: "IAA",
        1: "IRA",
        2: "PGI",
        3: "RSD",
        4: "RSL",
        5: "TCL",
        6: "TIO",
        7: "VRC",
    },
    "UNMAF": {
        0: "CIS",
        1: "CRA",
        2: "IOS",
        3: "IPS",
        4: "MFA",
        5: "MUS",
        6: "MVA",
        7: "PAI",
        8: "PDA",
        9: "PUO",
        10: "RNG",
        11: "STA",
        12: "UVA",
    },
    "UNSBS": {
        0: "RNO",
        1: "SBB",
        2: "SBS",
        3: "VGE",
    },
    "NULES": {
        0: "BBS",
        1: "BVS",
        2: "CBU",
        3: "CMB",
        4: "IFA",
        5: "IIA",
        6: "IMP",
        7: "ISS",
        8: "NGS",
        9: "PBO",
        10: "PCS",
    },
    "NUOES": {
        0: "ALL",
        1: "CCI",
        2: "CCO",
        3: "CSA",
        4: "PZO",
        5: "QLO",
        6: "SLO",
        7: "XXE",
    },
}

REGIONAIS = {
    "Agência": {
        1: 101,
        2: 201,
        3: 301,
        4: 401,
        5: 501,
        6: 601,
        7: 701,
        8: 801,
        10: 1001,
        11: 1101,
        13: 1301,
        14: 1401,
        15: 1501,
        16: 1601,
        17: 1701,
        18: 1801,
    },
    "Sigla": {
        1: "ARFLO",
        2: "ARBLU",
        3: "ARJOI",
        4: "ARLAG",
        5: "ARVID",
        6: "ARCON",
        7: "ARJSL",
        8: "ARJOA",
        10:"ARCRI",
        11:"ARSMO",
        13: "ARTUB",
        14: "ARRSL",
        15: "ARMAF",
        16: "ARSBS",
        17: "ARITA",
        18: "ARCHA",
    },
    "Núcleo": {
        1: "NUCAP",
        2: "NUVAL",
        3: "NUNOR",
        4: "NUPLA",
        5: "UNVID",
        6: "UNCON",
        7: "UNJSL",
        8: "NUMOS",
        10:"NUSUL",
        11:"UNSMO",
        13: "UNTUB",
        14: "UNRSL",
        15: "UNMAF",
        16: "UNSBS",
        17: "NULES",
        18: "NUOES",
    },
    "Siglas SIMO": {
        1: "FNS",
        2: "BNU",
        3: "JVE",
        4: "LGS",
        5: "VII",
        6: "CDA",
        7: "JGS",
        8: "JCA",
        10:"CUA",
        11:"SGE",
        13: "TRO",
        14: "RSL",
        15: "MFA",
        16: "SBS",
        17: "IAI",
        18: "CCO",
    },
    "Cidade": {
        1: "Florianópolis",
        2: "Blumenau",
        3: "Joinville",
        4: "Lages",
        5: "Videira",
        6: "Concórdia",
        7: "Jaraguá do Sul",
        8: "Joaçaba",
        10:"Criciúma",
        11:"São Miguel do Oeste",
        13: "Tubarão",
        14: "Rio do Sul",
        15: "Mafra",
        16: "São Bento do Sul",
        17: "Itajaí",
        18: "Chapecó",
    },
}
